### ISSUE TITLE
Question mouseover tooltip UX

### ISSUE THREAD

**Issue by thoufer** [thoufer/harvestVis_demo#2]
Something to better direct users to the answers for the mouse-over questions.  

One user suggested some sort of true false question that would prompt users to mouse or click in the appropriate spot.

**Comment by asussman52** [comment]
Added an info icon to each tooltip. The mouse changes from a 'pointer' to a 'hand'.

Not sure how we'd make all these into true/false questions, but I'm not opposed to making it a click event instead of a mouse-over.
