### ISSUE TITLE
Counties.csv file needs update

### ISSUE THREAD

**Issue by thoufer** [thoufer/harvestVis_demo#22]
The resulting counties.csv file must have 3147 lines.  currently it is missing rows for counties with fips codes 15XXX and 2XXX (Hawaii and Alaska, i think).

The id in the json map are such that all fips code are left padded with 0 to be 5 digits.

**Comment by embuco** [comment]
The file you gave me has 3146 lines ?? what is the missing FIPS?

**Comment by thoufer** [comment]
That should be correct.. I think I forgot that the header is line 1.

N.
---------------------------------------
US Fish and Wildlife Service
Division of Migratory Bird Management
11510 American Holly Dr.
Laurel MD 20708

301-497-5869 (phone)
301-497-5871 (fax)
https://www.fws.gov/birds
