### ISSUE TITLE
change tooltip text

### ISSUE THREAD

**Issue by embuco** [thoufer/harvestVis_demo#35]
to "out of 3115 in the U.S." (maybe cut word "counties" as not quite right?)

**Comment by asussman52** [comment]
Also, when you toggle from duck to goose (or v-v), the popup remains from your previous selection, and then it's not necessarily clear whether that popup info corresponds to duck or goose. So, either need to add text to the popup that says DUCK or GOOSE, or remove the popup when toggling between duck/goose.

**Comment by thoufer** [comment]
Yes..

There is some conflict going on between the visualizations that causing the
tooltip to not be removed when toggling..
